export const pets = [
    {
      id: 1,
      name: "Susie",
      gender: "female",
      specie: "cats",
      breed: "British",
      imageSrc: "./images/cat.png",
      age: 11,
    },
    {
      id: 2,
      name: "Max",
      gender: "boy",
      specie: "dogs",
      breed: "Golden Retriever",
      imageSrc: "./images/dog.png",
      age: 5,
    },
    {
      id: 3,
      name: "Bella",
      gender: "female",
      specie: "dogs",
      breed: "Bulldog",
      imageSrc: "./images/dog.png",
      age: 12,
    },
    {
      id: 4,
      name: "Oscar",
      gender: "boy",
      specie: "cats",
      breed: "Siamese",
      imageSrc: "./images/cat.png",
      age: 2,
    },
    {
      id: 5,
      name: "Luna",
      gender: "female",
      specie: "dogs",
      breed: "Poodle",
      imageSrc: "./images/dog.png",
      age: 9,
    },
    {
      id: 6,
      name: "Charlie",
      gender: "boy",
      specie: "dogs",
      breed: "Labrador",
      imageSrc: "./images/dog.png",
      age: 13,
    },
    {
      id: 7,
      name: "Milo",
      gender: "boy",
      specie: "cats",
      breed: "Persian",
      imageSrc: "./images/cat.png",
      age: 1,
    },
    {
      id: 8,
      name: "Daisy",
      gender: "female",
      specie: "dogs",
      breed: "Beagle",
      imageSrc: "./images/dog.png",
      age: 4,
    },
    {
      id: 9,
      name: "Lucy",
      gender: "female",
      specie: "cats",
      breed: "Maine Coon",
      imageSrc: "./images/cat.png",
      age: 14,
    },
    {
      id: 10,
      name: "Rocky",
      gender: "boy",
      specie: "dogs",
      breed: "Rottweiler",
      imageSrc: "./images/dog.png",
      age: 7,
    },
    {
      id: 11,
      name: "Tofinek",
      gender: "boy",
      specie: "dogs",
      breed: "Buldog",
      imageSrc: "./images/dog2.png",
      age: 4,
    },
    {
      id: 12,
      name: "Sigma",
      gender: "boy",
      specie: "other",
      breed: "snake",
      imageSrc: "./images/snake.png",
      age: 2,
    },
    {
      id: 13,
      name: "Alexandra",
      gender: "female",
      specie: "rabbits",
      breed: "rabbits",
      imageSrc: "./images/rabbit.png",
      age: 1,
    },
    {
      id: 14,
      name: "Koleś",
      gender: "boy",
      specie: "rabbits",
      breed: "rabbits",
      imageSrc: "./images/rabbit.png",
      age: 3,
    },
  ];
